import type { Timetable } from "./types";

const timetableId = "tt-aido-bscse-21-2026-s2";
const versionId = "ttv-aido-bscse-21-2026-s2-v3";
const timezone = "Africa/Harare";
const semesterStart = "2026-08-10";
const semesterEnd = "2026-12-04";

export const demoTimetable: Timetable = {
  id: timetableId,
  slug: "zou-bscse-2-1-2026-s2",
  title: "BSc Software Engineering Part 2.1",
  institution: "aiDo Demo University",
  campus: "Main Campus",
  faculty: "Faculty of Technology",
  department: "Department of Computer Science",
  programme: "BSc Software Engineering",
  part: "Part 2.1",
  groupName: "Group A",
  semester: "Semester 2, 2026",
  semesterStart,
  semesterEnd,
  timezone,
  version: "v3",
  source: "Department noticeboard and class representative CSV",
  verifiedBy: "T. Moyo, Programme Moderator",
  verificationStatus: "official",
  lastUpdated: "2026-08-03T09:20:00+02:00",
  publicFeedToken: "pub_eco_8fx3mQ2_demo_only",
  history: [
    {
      id: "v3",
      version: "v3",
      publishedAt: "2026-08-03T09:20:00+02:00",
      publishedBy: "T. Moyo",
      summary: "Venue corrected for Database Systems and Friday lab added.",
      severity: "major",
    },
    {
      id: "v2",
      version: "v2",
      publishedAt: "2026-07-29T15:00:00+02:00",
      publishedBy: "R. Dube",
      summary: "Operating Systems lecture moved from Wednesday to Thursday.",
      severity: "major",
    },
    {
      id: "v1",
      version: "v1",
      publishedAt: "2026-07-24T11:30:00+02:00",
      publishedBy: "R. Dube",
      summary: "Initial community verified timetable.",
      severity: "minor",
    },
  ],
  events: [
    {
      id: "bscse21-se201-mo-0800",
      timetableId,
      timetableVersionId: versionId,
      courseId: "se201",
      courseCode: "SE201",
      title: "Software Engineering",
      description: "Requirements modelling and sprint planning workshop.",
      location: "Innovation Hub, Room 3",
      lecturer: "Dr N. Chigora",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-10T08:00:00",
      endsAtLocal: "2026-08-10T10:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["MO"],
        until: semesterEnd,
      },
      exclusions: ["2026-09-14"],
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 3,
      lastModified: "2026-08-03T09:20:00+02:00",
    },
    {
      id: "bscse21-db202-tu-1000",
      timetableId,
      timetableVersionId: versionId,
      courseId: "db202",
      courseCode: "DB202",
      title: "Database Systems",
      description: "SQL design studio. Venue corrected in version v3.",
      location: "Lab 2",
      lecturer: "Eng. P. Nyathi",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-11T10:00:00",
      endsAtLocal: "2026-08-11T12:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["TU"],
        until: semesterEnd,
      },
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 3,
      lastModified: "2026-08-03T09:20:00+02:00",
    },
    {
      id: "bscse21-hci203-tu-1400",
      timetableId,
      timetableVersionId: versionId,
      courseId: "hci203",
      courseCode: "HCI203",
      title: "Human-Computer Interaction",
      location: "Design Studio",
      lecturer: "Ms A. Sibanda",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-11T14:00:00",
      endsAtLocal: "2026-08-11T16:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["TU"],
        until: semesterEnd,
      },
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 2,
      lastModified: "2026-07-29T15:00:00+02:00",
    },
    {
      id: "bscse21-os204-th-0800",
      timetableId,
      timetableVersionId: versionId,
      courseId: "os204",
      courseCode: "OS204",
      title: "Operating Systems",
      location: "Engineering Block, Room 12",
      lecturer: "Mr C. Maposa",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-13T08:00:00",
      endsAtLocal: "2026-08-13T10:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["TH"],
        until: semesterEnd,
      },
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 2,
      lastModified: "2026-07-29T15:00:00+02:00",
    },
    {
      id: "bscse21-net205-th-1100",
      timetableId,
      timetableVersionId: versionId,
      courseId: "net205",
      courseCode: "NET205",
      title: "Computer Networks",
      location: "Network Lab",
      lecturer: "Dr V. Zhou",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-13T11:00:00",
      endsAtLocal: "2026-08-13T13:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["TH"],
        until: semesterEnd,
      },
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 1,
      lastModified: "2026-07-24T11:30:00+02:00",
    },
    {
      id: "bscse21-se201-fr-0900",
      timetableId,
      timetableVersionId: versionId,
      courseId: "se201",
      courseCode: "SE201",
      title: "Software Engineering Lab",
      location: "Innovation Hub, Lab 1",
      lecturer: "Dr N. Chigora",
      groupName: "Group A",
      timezone,
      startsAtLocal: "2026-08-14T09:00:00",
      endsAtLocal: "2026-08-14T11:00:00",
      recurrence: {
        frequency: "weekly",
        interval: 1,
        weekdays: ["FR"],
        until: semesterEnd,
      },
      reminders: [720, 30],
      status: "confirmed",
      sourceUrl: "/t/zou-bscse-2-1-2026-s2",
      verificationStatus: "official",
      sequence: 3,
      lastModified: "2026-08-03T09:20:00+02:00",
    },
  ],
};

export const popularTimetables = [
  demoTimetable,
  {
    ...demoTimetable,
    id: "tt-aido-bcs-11",
    slug: "aido-bcs-1-1-2026-s2",
    programme: "BSc Computer Science",
    part: "Part 1.1",
    groupName: "Group B",
    verificationStatus: "community_verified" as const,
  },
  {
    ...demoTimetable,
    id: "tt-aido-it-31",
    slug: "aido-bit-3-1-2026-s2",
    programme: "BSc Information Technology",
    part: "Part 3.1",
    groupName: "Evening Class",
    verificationStatus: "draft" as const,
  },
];
